import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import BaseLayout from "@/components/BaseLayout";
import { getSession } from "@/lib/auth";
import SessionLayout from "@/components/SessionLayout";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-gray-900 text-black dark:text-white`}
      >
        <SessionLayout session={session}>
          <BaseLayout>{children}</BaseLayout>
        </SessionLayout>
      </body>
    </html>
  );
}
